server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/BackendSportify?serverTimezone=UTC&useSSL=false
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update

jwt:
    signerKey: "1t0gBYXKEMfj7YBSokSHymnat7CMQBB0gwhw7PnaGWbfHIZdwZ9oTKR2gk7otZWY"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds
